# Generated by Django 3.2.7 on 2022-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialProfits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maize_bran', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('cotton', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('sun_flower', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('fish', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('general_purpose_premix', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('layers_premix', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('shells', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('meat_boaster', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('egg_boaster', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('calcium', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('soya_bean', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('brown_salt', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('animal_salt', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('common_salt', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('pig_concentrate', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('coconut', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('wonder_pig', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('big_pig', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
            ],
        ),
    ]
