# Generated by Django 3.2.7 on 2022-08-08 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofits',
            name='broilers_marsh',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productprofits',
            name='chick_marsh',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productprofits',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='productprofits',
            name='growers_marsh',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productprofits',
            name='layers_marsh',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productprofits',
            name='pig_marsh',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productprofits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 8, 16, 37, 14, 514485)),
        ),
        migrations.AlterField(
            model_name='productquantities',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 8, 16, 37, 14, 511159)),
        ),
        migrations.AlterField(
            model_name='rawmaterialquantities',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 8, 16, 37, 14, 510495)),
        ),
    ]
