# Generated by Django 3.2.7 on 2022-01-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialquantities',
            name='salt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
