# Generated by Django 3.2.7 on 2022-01-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('onloading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offloading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grinding', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_of_supply', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='cost_of_supply',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='grinding',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='offloading',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='onloading',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='transport',
        ),
        migrations.AddField(
            model_name='product',
            name='animal_salt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='big_pig',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='brown_salt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='calcium',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='coconut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='common_salt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='pig_concentrate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='soya_bean',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='wonder_pig',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialprices',
            name='animal_salt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialprices',
            name='big_pig',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialprices',
            name='brown_salt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialprices',
            name='calcium',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialprices',
            name='coconut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialprices',
            name='common_salt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialprices',
            name='pig_concentrate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialprices',
            name='soya_bean',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialprices',
            name='wonder_pig',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialquantities',
            name='salt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
