# Generated by Django 3.2.7 on 2022-08-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment_terms',
            old_name='Agreed_salary',
            new_name='agreed_salary',
        ),
    ]
