# Generated by Django 3.2.7 on 2022-07-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0002_rawmaterialprofits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='animal_salt',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='big_pig',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='brown_salt',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='calcium',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='coconut',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='common_salt',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='cotton',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='egg_boaster',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='fish',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='general_purpose_premix',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='layers_premix',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='maize_bran',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='meat_boaster',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='pig_concentrate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='shells',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='soya_bean',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='sun_flower',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialprofits',
            name='wonder_pig',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
