# Generated by Django 3.2.7 on 2022-08-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0002_auto_20220824_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_material_transactions',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
