# Generated by Django 3.2.7 on 2022-01-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0002_auto_20220114_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='offloading',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='onloading',
        ),
    ]
