# Generated by Django 3.2.7 on 2022-08-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0002_rename_raw_material_sales_raw_material_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sales',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
