# Generated by Django 3.2.7 on 2022-08-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0002_rename_agreed_salary_employment_terms_agreed_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employment_advance',
            new_name='advance_payment',
        ),
        migrations.RenameField(
            model_name='employment_terms',
            old_name='Employee_id',
            new_name='employee_id',
        ),
    ]
