# Generated by Django 3.2.7 on 2022-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0003_product_sales_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
