# Generated by Django 3.2.7 on 2022-01-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0003_auto_20220114_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='cost_of_supply',
            new_name='total',
        ),
    ]
