# Generated by Django 3.2.7 on 2022-08-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedwork', '0004_expenses_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_payments',
            old_name='salary',
            new_name='salary_amount',
        ),
    ]
